apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lidarr-config
  namespace: mediamaven
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi  
  volumeName: pv-lidarr-config
  storageClassName: ""
