apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-deployment
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1026"  # Set appropriate user ID
            - name: PGID
              value: "1026"  # Set appropriate group ID
            - name: TZ
              value: "America/Chicago"  # Set your timezone
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              memory: "256Mi"   # Minimum amount of memory the container needs
              cpu: "250m"       # Minimum amount of CPU the container needs
            limits:
              memory: "512Mi"   # Maximum memory the container can use
              cpu: "500m"       # Maximum CPU the container can use
          livenessProbe:
            httpGet:
              path: / # Or /api/v3/system/status if a dedicated health endpoint is known
              port: 7878
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: / # Or /api/v3/system/status
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: pvc-radarr-config  # You can define a PVC if necessary
        - name: movies
          persistentVolumeClaim:
            claimName: pvc-movies
        - name: downloads
          persistentVolumeClaim:
            claimName: pvc-torrents
            readOnly: true
