apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-config
  namespace: mediamaven
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi  
  volumeName: pv-radarr-config
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-movies
  namespace: mediamaven
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Ti
  volumeName: pv-movies
  storageClassName: ""