---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
  namespace: webui
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "local-path"  # or your cluster's storage class
  resources:
    requests:
      storage: 5Gi