apiVersion: v1
kind: Secret
metadata:
  name: open-webui-config
  namespace: webui
type: Opaque
stringData:
  # generate a long random value and keep it stable across upgrades
  WEBUI_SECRET_KEY: "change-me-to-a-long-random-string"
  OLLAMA_BASE_URL: "http://ollama.default.svc.cluster.local:11434"
