---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: webui
  labels:
    app: open-webui
spec:
  selector:
    app: open-webui
  ports:
  - port: 8080
    targetPort: 8080
    name: open-webui
  type: LoadBalancer
