apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: webui
  labels:
    app: open-webui
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
  - name: http
    port: 80
    targetPort: 8080