apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-config
  namespace: mediamaven
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi  
  volumeName: pv-sonarr-config
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tv-shows
  namespace: mediamaven
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Ti
  volumeName: pv-tv-shows
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-downloads-sonarr
  namespace: mediamaven
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Ti
  volumeName: pv-downloads
  storageClassName: ""
