apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-transmission-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-transmission-config