apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n
          ports:
            - containerPort: 5678
          volumeMounts:
            - mountPath: "/home/node/.n8n"
              name: n8n-volume
          resources:
            requests:
              memory: "512Mi"  # Minimum memory required to run the container
              cpu: "250m"      # Minimum CPU required to run the container
            limits:
              memory: "2Gi"    # Maximum memory allowed
              cpu: "1000m"     # Maximum CPU allowed
      volumes:
        - name: n8n-volume
          persistentVolumeClaim:
            claimName: pvc-n8n