apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-n8n
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-n8n
  storageClassName: ""
