apiVersion: apps/v1
kind: Deployment
metadata:
  name: csvtoqxf-deployment
  labels:
    app: csvtoqxf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csvtoqxf
  template:
    metadata:
      labels:
        app: csvtoqxf
    spec:
      containers:
      - name: csvtoqxf
        image: terryalsdorf/csvtoqxf:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 1002 # Example non-root user ID, adjust if image uses a different UID or for volume permissions
          runAsGroup: 1002 # Example non-root group ID, adjust if image uses a different GID or for volume permissions
          # readOnlyRootFilesystem: true # Consider if the app supports it
          # capabilities: # Drop all capabilities if possible
          #   drop:
          #   - ALL
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "500m" # Allow some burst for conversion
            memory: "256Mi"
