apiVersion: v1
kind: Service
metadata:
  name: csvtoqxf-service
spec:
  selector:
    app: csvtoqxf
  ports:
    - protocol: TCP
      port: 8314       # Service port
      targetPort: 5000 # Container port
  type: ClusterIP