apiVersion: v1
kind: Service
metadata:
  name: csvtoqxf-service
  labels:
    app: csvtoqxf
spec:
  type: LoadBalancer
  selector:
    app: csvtoqxf
  ports:
    - protocol: TCP
      port: 8314       # Service port
      targetPort: 5000 # Container port
      name: csvtoqxf
