apiVersion: v1
kind: Service
metadata:
  name: jackett-service
  labels:
    app: jackett
spec:
  type: LoadBalancer
  selector:
    app: jackett
  ports:
    - protocol: TCP
      port: 9117
      targetPort: 9117
      name: jackett
 
